# Generated by Django 4.2.6 on 2023-11-01 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 1, 18, 22, 14, 171125), verbose_name='Дата создания'),
        ),
    ]
