# Generated by Django 4.2.6 on 2023-11-03 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 17, 24, 4, 864375), verbose_name='Дата создания'),
        ),
    ]
