# Generated by Django 4.2.6 on 2023-11-03 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_mailing_next_attempt_alter_mailing_interval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=100, verbose_name='Тема рассылки')),
                ('body', models.TextField(verbose_name='Содержание рассылки')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
        migrations.RemoveField(
            model_name='logs',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='body',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='subject',
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mailings.message', verbose_name='Сообщение'),
        ),
    ]
